                                                             
services:

  pigpiod:
    image: zinen2/alpine-pigpiod
    container_name: pigpiod
    privileged: true
    networks:
      - node-red

  node-red:
    image: sheng2216/nodered-docker:alpine-latest
    container_name: node-red
    user: node-red
    group_add:
      - 998
    networks:
      - node-red
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    restart: unless-stopped
    volumes:
      - node-red-data:/data
    devices:
      - "/dev/i2c-1:/dev/i2c-1"


volumes:
  node-red-data:

networks:
  node-red:
