version: '2'

services:

  pigpiod:
    image: zinen2/alpine-pigpiod
    container_name: pigpiod
    privileged: true
    networks:
      - node-red

  nodered:
    image: nodered/node-red:2.2.2
    container_name: NodeRed
    restart: unless-stopped
    privileged: true
    user: node-red
    group_add:
        - 998
    environment:
      - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
        - 'node-red-data:/data'
    ports:
        - "1880:1880/tcp"
   

volumes:
  node-red-data:

networks:
  node-red:
