version: "2"

services:

  pigpiod:
    image: zinen2/alpine-pigpiod
    container_name: pigpiod
    privileged: true
    restart: unless-stopped
    networks:
      - node-red

  nodered:
    image: sheng2216/nodered-docker:alpine-latest
    container_name: NodeRed
    restart: unless-stopped
    user: node-red
    group_add:
      - 998
    environment:
      - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - node-red-data:/data
    ports:
      - "1880:1880"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    networks:
      - node-red

volumes:
  node-red-data:

networks:
  node-red:
