version: '2'

services:

  nodered:
    image: sheng2216/nodered-docker:alpine-latest
    container_name: NodeRed
    restart: unless-stopped
    user: node-red
    group_add:
        - 998
    environment:
        - NODE_RED_ENABLE_PROJECTS=false
        - PUID=1000
        - PGID=100
        - TZ=Europe/Paris
    volumes:
        - 'node-red-data:/data'
    ports:
        - "1880:1880/tcp"
    devices:
        - "/dev/vcio:/dev/vcio"
        - "/dev/mem:/dev/mem"
        - "/dev/i2c-1:/dev/i2c-1"
    cap_add:
      - CAP_SYS_RAWIO

volumes:
  node-red-data:
